name: Build iOS app
on: push

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get short commit SHA
        run: echo SHORT_SHA=$(git rev-parse --short HEAD) >> $env:GITHUB_ENV

      - name: Build app
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          cd ./native/metrodroid
          xcodebuild -project metrodroid.xcodeproj -scheme metrodroid -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Archive app
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          cd ./native/metrodroid
          xcodebuild archive -project metrodroid.xcodeproj -scheme metrodroid -archivePath metrodroid_unsigned.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Create ipa
        run: |
          cd ./native/metrodroid
          mkdir Payload
          cp -r metrodroid_unsigned.xcarchive/Products/Applications/metrodroid.app Payload/
          zip metrodroid_unsigned.ipa Payload

      - name: Zip xcarchive
        run: |
          cd ./native/metrodroid
          zip -r metrodroid_unsigned.xcarchive.zip metrodroid_unsigned.xcarchive

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 #v1
        with:
          files: |
            ./native/metrodroid/metrodroid_unsigned.ipa
            ./native/metrodroid/metrodroid_unsigned.xcarchive.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup upterm session
        if: failed()
        uses: mxschmitt/action-tmate@v3
